/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_josericardojunior_Native_MatrixProcessor */

#ifndef _Included_com_josericardojunior_Native_MatrixProcessor
#define _Included_com_josericardojunior_Native_MatrixProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_josericardojunior_Native_MatrixProcessor
 * Method:    CPUMatMult
 * Signature: ([F[FIII)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_josericardojunior_Native_MatrixProcessor_CPUMatMult
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jint, jint, jint);

/*
 * Class:     com_josericardojunior_Native_MatrixProcessor
 * Method:    BLASMatMult
 * Signature: ([F[FIII)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_josericardojunior_Native_MatrixProcessor_BLASMatMult
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jint, jint, jint);

/*
 * Class:     com_josericardojunior_Native_MatrixProcessor
 * Method:    GPUMatMult
 * Signature: ([F[FIII)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_josericardojunior_Native_MatrixProcessor_GPUMatMult
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jint, jint, jint);

/*
 * Class:     com_josericardojunior_Native_MatrixProcessor
 * Method:    GPUStandardScore
 * Signature: ([FIII[F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_josericardojunior_Native_MatrixProcessor_GPUStandardScore
  (JNIEnv *, jclass, jfloatArray, jint, jint, jint, jfloatArray);

/*
 * Class:     com_josericardojunior_Native_MatrixProcessor
 * Method:    CPUStandardScore
 * Signature: ([FIII[F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_josericardojunior_Native_MatrixProcessor_CPUStandardScore
  (JNIEnv *, jclass, jfloatArray, jint, jint, jint, jfloatArray);

/*
 * Class:     com_josericardojunior_Native_MatrixProcessor
 * Method:    GPUMeanSD
 * Signature: ([FIIIZ)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_josericardojunior_Native_MatrixProcessor_GPUMeanSD
  (JNIEnv *, jclass, jfloatArray, jint, jint, jint, jboolean);

/*
 * Class:     com_josericardojunior_Native_MatrixProcessor
 * Method:    CPUMeanSD
 * Signature: ([FIIIZ)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_josericardojunior_Native_MatrixProcessor_CPUMeanSD
  (JNIEnv *, jclass, jfloatArray, jint, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
