/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_josericardojunior_Native_MatrixProcessor_Processor */

#ifndef _Included_com_josericardojunior_Native_MatrixProcessor_Processor
#define _Included_com_josericardojunior_Native_MatrixProcessor_Processor
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
