/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_josericardojunior_Native_MatrixProcessor */

#ifndef _Included_com_josericardojunior_Native_MatrixProcessor
#define _Included_com_josericardojunior_Native_MatrixProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_josericardojunior_Native_MatrixProcessor
 * Method:    CPUMatMult
 * Signature: ([F[FIII)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_josericardojunior_Native_MatrixProcessor_CPUMatMult
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jint, jint, jint);

/*
 * Class:     com_josericardojunior_Native_MatrixProcessor
 * Method:    BLASMatMult
 * Signature: ([F[FIII)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_josericardojunior_Native_MatrixProcessor_BLASMatMult
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jint, jint, jint);

/*
 * Class:     com_josericardojunior_Native_MatrixProcessor
 * Method:    GPUMatMult
 * Signature: ([F[FIII)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_josericardojunior_Native_MatrixProcessor_GPUMatMult
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jint, jint, jint);

/*
 * Class:     com_josericardojunior_Native_MatrixProcessor
 * Method:    GPUStandardScore
 * Signature: ([FIII[F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_josericardojunior_Native_MatrixProcessor_GPUStandardScore
  (JNIEnv *, jclass, jfloatArray, jint, jint, jint, jfloatArray);

/*
 * Class:     com_josericardojunior_Native_MatrixProcessor
 * Method:    CPUStandardScore
 * Signature: ([FIII[F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_josericardojunior_Native_MatrixProcessor_CPUStandardScore
  (JNIEnv *, jclass, jfloatArray, jint, jint, jint, jfloatArray);

/*
 * Class:     com_josericardojunior_Native_MatrixProcessor
 * Method:    GPUMeanSD
 * Signature: ([FIIIZ)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_josericardojunior_Native_MatrixProcessor_GPUMeanSD
  (JNIEnv *, jclass, jfloatArray, jint, jint, jint, jboolean);

/*
 * Class:     com_josericardojunior_Native_MatrixProcessor
 * Method:    CPUMeanSD
 * Signature: ([FIIIZ)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_josericardojunior_Native_MatrixProcessor_CPUMeanSD
  (JNIEnv *, jclass, jfloatArray, jint, jint, jint, jboolean);

/*
 * Class:     com_josericardojunior_Native_MatrixProcessor
 * Method:    createMatrixData
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_josericardojunior_Native_MatrixProcessor_createMatrixData
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_josericardojunior_Native_MatrixProcessor
 * Method:    setData
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_com_josericardojunior_Native_MatrixProcessor_setData
  (JNIEnv *, jclass, jlong, jfloatArray);

/*
 * Class:     com_josericardojunior_Native_MatrixProcessor
 * Method:    setRowData
 * Signature: (J[FI)V
 */
JNIEXPORT void JNICALL Java_com_josericardojunior_Native_MatrixProcessor_setRowData
  (JNIEnv *, jclass, jlong, jfloatArray, jint);

/*
 * Class:     com_josericardojunior_Native_MatrixProcessor
 * Method:    getRow
 * Signature: (JI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_josericardojunior_Native_MatrixProcessor_getRow
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_josericardojunior_Native_MatrixProcessor
 * Method:    getData
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_josericardojunior_Native_MatrixProcessor_getData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_josericardojunior_Native_MatrixProcessor
 * Method:    deleteMatrixData
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_josericardojunior_Native_MatrixProcessor_deleteMatrixData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_josericardojunior_Native_MatrixProcessor
 * Method:    multiply
 * Signature: (JJJZ)V
 */
JNIEXPORT void JNICALL Java_com_josericardojunior_Native_MatrixProcessor_multiply
  (JNIEnv *, jclass, jlong, jlong, jlong, jboolean);

/*
 * Class:     com_josericardojunior_Native_MatrixProcessor
 * Method:    transpose
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_josericardojunior_Native_MatrixProcessor_transpose
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
